name: Test and Publish to NPM

on:
  release:
    types:
      - created
      - edited

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: yarn install 
      - name: Run tests
        run: yarn test

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm publish
